### ISSUE TITLE
Wrong keywords in forwardingList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/OperationKeyManagement#195]
I noticed that in the forwarding list there are keywords "server-name" and "service-name".
In the template from the ApplicationPattern I only see "server-name", so I guess this might be wrong as I would expect this should be "server-name" everywhere...

Example:
```
  - forwarding-name: ServiceRequestCausesLoggingRequest
    uuid: okm-2-0-1-op-fc-bm-002
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/redirect-service-request-information
          uuid: okm-2-0-1-op-s-bm-002
      fc-port-update:
        - server-name: /v1/redirect-service-request-information
          uuid: okm-2-0-1-op-s-bm-002
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
...
      - server-name: /v1/inform-about-release-history
        uuid: okm-2-0-1-op-s-bs-003
      - server-name: /v1/inform-about-release-history-in-generic-representation
        uuid: okm-2-0-1-op-s-bs-004
      - service-name: /v1/regard-application
        uuid: okm-2-0-1-op-s-is-001
      - service-name: /v1/disregard-application
        uuid: okm-2-0-1-op-s-is-002
      - service-name: /v1/list-applications
        uuid: okm-2-0-1-op-s-is-003
      - service-name: /v1/regard-updated-link
        uuid: okm-2-0-1-op-s-is-004
    consequent-requests:
      - client-name: ExecutionAndTraceLog://v1/record-service-request
        uuid: okm-2-0-1-op-c-bs-eatl-1-0-0-000
```
